"""Requirement 4 - a self-contained HTML preview of the finished rig.

The skeleton JSON, ``.atlas`` and PNG are inlined as base64 data URIs and handed
to the Spine Web Player through ``rawDataURIs``, so the file works from
``file://`` with no server and no sibling assets.

The runtime itself is handled carefully. The Spine Runtimes License restricts
redistribution and requires the viewer to hold a Spine license, so OCS does not
commit ``spine-player.js``. If ``scripts/fetch_spine_player.ps1`` has put it in
``web/vendor/`` it is inlined and the page is fully offline; otherwise the page
falls back to loading it from unpkg at view time. See NOTICE.md.
"""

from __future__ import annotations

import base64
import json
from pathlib import Path

from .config import SPINE_PLAYER_CDN_CSS, SPINE_PLAYER_CDN_JS, VENDOR_DIR

_TEMPLATE = """<meta charset="utf-8">
<title>{title}</title>
{head}
<style>
  :root {{ color-scheme: dark; }}
  * {{ box-sizing: border-box; }}
  body {{
    margin: 0; min-height: 100vh; display: flex; flex-direction: column;
    background: #14161a; color: #e6e8ec;
    font: 14px/1.5 "Segoe UI", system-ui, -apple-system, sans-serif;
  }}
  header {{
    display: flex; align-items: baseline; gap: 12px; flex-wrap: wrap;
    padding: 14px 20px; border-bottom: 1px solid #262a31; background: #181b20;
  }}
  header h1 {{ margin: 0; font-size: 15px; font-weight: 600; letter-spacing: .01em; }}
  header .meta {{ color: #8b929e; font-size: 12px; }}
  header .meta b {{ color: #c9cfd8; font-weight: 600; }}
  #stage {{ flex: 1; min-height: 480px; position: relative; }}
  .spine-player {{ position: absolute; inset: 0; }}
  #fallback {{
    display: none; padding: 20px; margin: 20px; border-radius: 8px;
    background: #2a1d1d; border: 1px solid #5c3434; color: #f0c8c8;
  }}
  footer {{ padding: 10px 20px; color: #6c7280; font-size: 11px; border-top: 1px solid #262a31; }}
</style>

<header>
  <h1>{title}</h1>
  <span class="meta"><b>{bones}</b> bones &middot; <b>{slots}</b> slots &middot;
    <b>{meshes}</b> meshes &middot; atlas <b>{atlas_w}&times;{atlas_h}</b></span>
</header>
<div id="stage"></div>
<div id="fallback"></div>
<footer>Generated by OCS (OneClickSpine). Rendered with the Spine Web Player,
&copy; Esoteric Software &mdash; use requires your own Spine license.</footer>

<script>
const OCS = {{
  skeleton: "{skeleton_uri}",
  atlas: "{atlas_uri}",
  png: "{png_uri}",
  animations: {animations},
  animation: {animation},
}};

function fail(msg) {{
  const el = document.getElementById("fallback");
  el.style.display = "block";
  el.textContent = msg;
}}

function boot() {{
  if (typeof spine === "undefined" || !spine.SpinePlayer) {{
    fail("Spine Web Player runtime unavailable. Run scripts/fetch_spine_player.ps1 "
       + "to embed it for offline use, or open this page with internet access.");
    return;
  }}
  new spine.SpinePlayer("stage", {{
    jsonUrl: "skeleton.json",
    atlasUrl: "skeleton.atlas",
    rawDataURIs: {{
      "skeleton.json": OCS.skeleton,
      "skeleton.atlas": OCS.atlas,
      "skeleton.png": OCS.png,
    }},
    animation: OCS.animation || undefined,
    animations: OCS.animations,
    premultipliedAlpha: false,
    backgroundColor: "#14161a",
    alpha: true,
    showControls: {controls},
    debug: false,
    success: (p) => {{ window.__ocsPlayer = p; document.body.dataset.ocsReady = "1"; }},
    error: (_p, msg) => fail("Spine player error: " + msg),
  }});
}}

if (document.readyState === "loading") {{
  document.addEventListener("DOMContentLoaded", boot);
}} else {{
  boot();
}}
</script>
"""


def _data_uri(path: Path, mime: str) -> str:
    blob = base64.b64encode(path.read_bytes()).decode("ascii")
    return f"data:{mime};base64,{blob}"


def _runtime_head() -> tuple[str, bool]:
    """Inline the vendored runtime when present, else point at the CDN."""
    js = VENDOR_DIR / "spine-player.js"
    css = VENDOR_DIR / "spine-player.css"
    if js.exists() and js.stat().st_size > 1024:
        head = ""
        if css.exists():
            head += f"<style>{css.read_text(encoding='utf-8', errors='replace')}</style>\n"
        head += f"<script>{js.read_text(encoding='utf-8', errors='replace')}</script>"
        return head, True
    return (
        f'<link rel="stylesheet" href="{SPINE_PLAYER_CDN_CSS}">\n'
        f'<script src="{SPINE_PLAYER_CDN_JS}"></script>',
        False,
    )


def build_preview(
    skeleton_json: str | Path,
    atlas_file: str | Path,
    atlas_png: str | Path,
    out_path: str | Path,
    title: str = "OCS preview",
    animation: str | None = "idle",
    controls: bool = True,
) -> tuple[Path, bool]:
    """Write a standalone preview. Returns (path, runtime_is_embedded)."""
    skeleton_json, atlas_file, atlas_png = Path(skeleton_json), Path(atlas_file), Path(atlas_png)
    doc = json.loads(skeleton_json.read_text(encoding="utf-8"))

    animations = sorted(doc.get("animations", {}))
    if animation not in animations:
        animation = animations[0] if animations else None

    meshes = sum(
        1
        for entries in (doc.get("skins") or [{}])[0].get("attachments", {}).values()
        for body in entries.values()
        if body.get("type") == "mesh"
    )
    size = (0, 0)
    for line in atlas_file.read_text(encoding="utf-8").splitlines():
        if line.startswith("size:"):
            w, h = line.split(":", 1)[1].split(",")
            size = (int(w), int(h))
            break

    head, embedded = _runtime_head()
    html = _TEMPLATE.format(
        title=title,
        head=head,
        bones=len(doc.get("bones", [])),
        slots=len(doc.get("slots", [])),
        meshes=meshes,
        atlas_w=size[0],
        atlas_h=size[1],
        skeleton_uri=_data_uri(skeleton_json, "application/json"),
        atlas_uri=_data_uri(atlas_file, "application/octet-stream"),
        png_uri=_data_uri(atlas_png, "image/png"),
        animations=json.dumps(animations),
        animation=json.dumps(animation),
        controls="true" if controls else "false",
    )

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(html, encoding="utf-8")
    return out_path, embedded
